name: Fetch, build and deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fetching branch
        uses: actions/checkout@v2.3.1
        with:
          ref: master

      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pug_watcher

      - name: Compile Pug code
        run: pug_watcher --config

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
          clean: true
