name: Fetch, build and deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fetching branch
        uses: actions/checkout@v2.3.1
        with:
          ref: master

      - name: Installing NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Installing Yarn
        run: npm install -g yarn

      - name: Installing package.json
        run: yarn install

      - name: Building and exporting
        run: yarn github

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: out
          clean: true
